/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class Admin_GUI extends javax.swing.JFrame {
    
    int btnClicked = 1;
    
    /**
     * Creates new form Admin_GUI
     */
    public Admin_GUI() {
        initComponents();
        
        TrangChu_GUI pnTrangChu = new TrangChu_GUI();
        showPanel(pnTrangChu);
        
        btnClicked();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        btnQuanLyNV = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnQuanLyKH = new javax.swing.JButton();
        btnQuanLyNCC = new javax.swing.JButton();
        btnQuanLySP = new javax.swing.JButton();
        btnQuanLyDM = new javax.swing.JButton();
        btnQuanLyHD = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnTrangChu = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setBackground(new java.awt.Color(0, 126, 167));

        pnMenu.setBackground(new java.awt.Color(102, 163, 222));

        btnQuanLyNV.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyNV.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-staff-26.png"))); // NOI18N
        btnQuanLyNV.setText("Quản lý nhân viên");
        btnQuanLyNV.setBorder(null);
        btnQuanLyNV.setBorderPainted(false);
        btnQuanLyNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyNVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyNVMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyNVMouseEntered(evt);
            }
        });
        btnQuanLyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNVActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(255, 204, 0));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-rounded-left-26.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(null);
        btnDangXuat.setBorderPainted(false);
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseExited(evt);
            }
        });
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnQuanLyKH.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-groups-26.png"))); // NOI18N
        btnQuanLyKH.setText("Quản lý khách hàng");
        btnQuanLyKH.setBorder(null);
        btnQuanLyKH.setBorderPainted(false);
        btnQuanLyKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyKHMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyKHMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyKHMouseEntered(evt);
            }
        });
        btnQuanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKHActionPerformed(evt);
            }
        });

        btnQuanLyNCC.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyNCC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-truck-26.png"))); // NOI18N
        btnQuanLyNCC.setText("Quản lý nhà cung cấp");
        btnQuanLyNCC.setBorder(null);
        btnQuanLyNCC.setBorderPainted(false);
        btnQuanLyNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNCC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseEntered(evt);
            }
        });
        btnQuanLyNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNCCActionPerformed(evt);
            }
        });

        btnQuanLySP.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLySP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLySP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-product-26.png"))); // NOI18N
        btnQuanLySP.setText("Quản lý sản phẩm");
        btnQuanLySP.setBorder(null);
        btnQuanLySP.setBorderPainted(false);
        btnQuanLySP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLySP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLySPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLySPMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLySPMouseEntered(evt);
            }
        });
        btnQuanLySP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySPActionPerformed(evt);
            }
        });

        btnQuanLyDM.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyDM.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyDM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-product-management-26.png"))); // NOI18N
        btnQuanLyDM.setText("Quản lý danh mục");
        btnQuanLyDM.setBorder(null);
        btnQuanLyDM.setBorderPainted(false);
        btnQuanLyDM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyDMMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyDMMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyDMMouseEntered(evt);
            }
        });
        btnQuanLyDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDMActionPerformed(evt);
            }
        });

        btnQuanLyHD.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyHD.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-receipt-26.png"))); // NOI18N
        btnQuanLyHD.setText("Quản lý hóa đơn");
        btnQuanLyHD.setBorder(null);
        btnQuanLyHD.setBorderPainted(false);
        btnQuanLyHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyHDMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyHDMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyHDMouseEntered(evt);
            }
        });
        btnQuanLyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHDActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(128, 216, 255));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-account-26.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setBorder(null);
        btnThongKe.setBorderPainted(false);
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-1.png"))); // NOI18N

        btnTrangChu.setBackground(new java.awt.Color(128, 216, 255));
        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-home-26.png"))); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setBorder(null);
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.setInheritsPopupMenu(true);
        btnTrangChu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTrangChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLyNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLyKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLyNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLySP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLyDM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLyHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMenuLayout.createSequentialGroup()
                                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addComponent(jSeparator2)
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyNV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyKH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLySP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyDM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLyHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //Start show Panel
    private void btnQuanLyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNVActionPerformed
        QuanLyNhanVien_GUI pnQLNV = new QuanLyNhanVien_GUI();

        showPanel(pnQLNV);
    }//GEN-LAST:event_btnQuanLyNVActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        DangNhap_GUI frmDangNhap = new DangNhap_GUI();
        
        frmDangNhap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQuanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKHActionPerformed
        QuanLyKhachHang_GUI pnQLKH = new QuanLyKhachHang_GUI();

        showPanel(pnQLKH);
    }//GEN-LAST:event_btnQuanLyKHActionPerformed

    private void btnQuanLyNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNCCActionPerformed
        QuanLyNCC_GUI pnQLNCC = new QuanLyNCC_GUI();

        showPanel(pnQLNCC);
    }//GEN-LAST:event_btnQuanLyNCCActionPerformed

    private void btnQuanLySPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySPActionPerformed
        QuanLySanPham_GUI pnQLSP = new QuanLySanPham_GUI();

        showPanel(pnQLSP);
    }//GEN-LAST:event_btnQuanLySPActionPerformed

    private void btnQuanLyDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDMActionPerformed
        QuanLyDanhMuc_GUI pnQLDM = new QuanLyDanhMuc_GUI();

        showPanel(pnQLDM);
    }//GEN-LAST:event_btnQuanLyDMActionPerformed

    private void btnQuanLyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHDActionPerformed
        QuanLyHoaDon_GUI pnQLHD = new QuanLyHoaDon_GUI();

        showPanel(pnQLHD);
    }//GEN-LAST:event_btnQuanLyHDActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        ThongKe_GUI pnThongKe = new ThongKe_GUI();

        showPanel(pnThongKe);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        TrangChu_GUI pnTrangChu = new TrangChu_GUI();
        
        showPanel(pnTrangChu);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    //End show Panel
    
    
    //Start Hover button
    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseEntered
        btnColorHover(btnTrangChu);
        //btnTrangChu.setBackground(new Color(0,255,153)); //hover Xanh lá
    }//GEN-LAST:event_btnTrangChuMouseEntered

    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseExited
        if (btnClicked != 1){
            btnColorOrigin(btnTrangChu);
        }
    }//GEN-LAST:event_btnTrangChuMouseExited

    private void btnQuanLyNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNVMouseEntered
        btnColorHover(btnQuanLyNV);
    }//GEN-LAST:event_btnQuanLyNVMouseEntered

    private void btnQuanLyNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNVMouseExited
        if (btnClicked != 2){
            btnColorOrigin(btnQuanLyNV);
        }
    }//GEN-LAST:event_btnQuanLyNVMouseExited

    private void btnQuanLyKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyKHMouseEntered
        btnColorHover(btnQuanLyKH);
    }//GEN-LAST:event_btnQuanLyKHMouseEntered

    private void btnQuanLyKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyKHMouseExited
        if (btnClicked != 3){
            btnColorOrigin(btnQuanLyKH);
        }
    }//GEN-LAST:event_btnQuanLyKHMouseExited

    private void btnQuanLyNCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseEntered
        btnColorHover(btnQuanLyNCC);
    }//GEN-LAST:event_btnQuanLyNCCMouseEntered

    private void btnQuanLyNCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseExited
        if (btnClicked != 4){
            btnColorOrigin(btnQuanLyNCC);
        }
    }//GEN-LAST:event_btnQuanLyNCCMouseExited

    private void btnQuanLySPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySPMouseEntered
        btnColorHover(btnQuanLySP);
    }//GEN-LAST:event_btnQuanLySPMouseEntered

    private void btnQuanLySPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySPMouseExited
        if (btnClicked != 5){
            btnColorOrigin(btnQuanLySP);
        }
    }//GEN-LAST:event_btnQuanLySPMouseExited

    private void btnQuanLyDMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyDMMouseEntered
        btnColorHover(btnQuanLyDM);
    }//GEN-LAST:event_btnQuanLyDMMouseEntered

    private void btnQuanLyDMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyDMMouseExited
        if (btnClicked != 6){
            btnColorOrigin(btnQuanLyDM);
        }
    }//GEN-LAST:event_btnQuanLyDMMouseExited

    private void btnQuanLyHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHDMouseEntered
        btnColorHover(btnQuanLyHD);
    }//GEN-LAST:event_btnQuanLyHDMouseEntered

    private void btnQuanLyHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHDMouseExited
        if (btnClicked != 7){
            btnColorOrigin(btnQuanLyHD);
        }
    }//GEN-LAST:event_btnQuanLyHDMouseExited

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
        btnColorHover(btnThongKe);
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        if (btnClicked != 8){
            btnColorOrigin(btnThongKe);
        }   
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseEntered
        btnDangXuat.setBackground(new Color(255,204,102)); //Cam nhat
    }//GEN-LAST:event_btnDangXuatMouseEntered

    private void btnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseExited
        btnDangXuat.setBackground(new Color(255,204,0)); //Cam
    }//GEN-LAST:event_btnDangXuatMouseExited

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        btnClicked = 8;
        btnClicked();
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void btnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseClicked
        btnClicked = 1;
        btnClicked();
    }//GEN-LAST:event_btnTrangChuMouseClicked

    private void btnQuanLyNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNVMouseClicked
        btnClicked = 2;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyNVMouseClicked

    private void btnQuanLyKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyKHMouseClicked
        btnClicked = 3;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyKHMouseClicked

    private void btnQuanLyNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseClicked
        btnClicked = 4;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyNCCMouseClicked

    private void btnQuanLySPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySPMouseClicked
        btnClicked = 5;
        btnClicked();
    }//GEN-LAST:event_btnQuanLySPMouseClicked

    private void btnQuanLyDMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyDMMouseClicked
        btnClicked = 6;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyDMMouseClicked

    private void btnQuanLyHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHDMouseClicked
        btnClicked = 7;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyHDMouseClicked
    //End Hover button
    
    
    private void showPanel(JPanel panelName){       
        pnMain.removeAll();
        pnMain.add(panelName);
        pnMain.validate();
    }
    
    private void btnColorHover(JButton btnName){
        btnName.setBackground(new Color(0,255,153));//Xanh la
    }
    
    private void btnColorOrigin(JButton btnName){
        btnName.setBackground(new Color(128,216,255)); //Xanh duong
    }
    
    private void btnClicked(){
        if (btnClicked == 1){
            btnColorHover(btnTrangChu);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 2){
            btnColorHover(btnQuanLyNV);
            
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 3){
            btnColorHover(btnQuanLyKH);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 4){
            btnColorHover(btnQuanLyNCC);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 5){
            btnColorHover(btnQuanLySP);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 6){
            btnColorHover(btnQuanLyDM);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 7){
            btnColorHover(btnQuanLyHD);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnThongKe);
        }
        
        if (btnClicked == 8){
            btnColorHover(btnThongKe);
            
            btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnTrangChu);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQuanLyDM;
    private javax.swing.JButton btnQuanLyHD;
    private javax.swing.JButton btnQuanLyKH;
    private javax.swing.JButton btnQuanLyNCC;
    private javax.swing.JButton btnQuanLyNV;
    private javax.swing.JButton btnQuanLySP;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    // End of variables declaration//GEN-END:variables
}
